import {
  ConversionOptions,
  ConversionResult,
  ConversionStats,
  PlaygroundBlueprint,
  SourceFile,
  VisualTagBinding,
  WordPressThemeFile,
  WordPressThemeMeta,
} from '../../types';
import { sanitizeSlug, toPhpPrefix } from './php';

/**
 * Generates Advanced Custom Fields (ACF) Local JSON export file
 */
export function generateAcfJsonGroup(meta: WordPressThemeMeta, options: ConversionOptions): string {
  const prefix = toPhpPrefix(meta.textDomain || meta.name);
  
  const defaultFields = [
    {
      key: `field_${prefix}_hero_badge`,
      label: 'Hero Badge Text',
      name: 'hero_badge_text',
      type: 'text',
      instructions: 'Optional badge or pill label displayed above the main headline.',
      required: 0,
      default_value: 'WordPress Engineering',
      placeholder: 'e.g. New Release',
    },
    {
      key: `field_${prefix}_hero_subtitle`,
      label: 'Hero Subtitle / Description',
      name: 'hero_subtitle',
      type: 'textarea',
      instructions: 'Sub-headline or paragraph under the hero title.',
      required: 0,
      rows: 3,
      default_value: 'Empowering creators and brands with modern WordPress engineering.',
    },
    {
      key: `field_${prefix}_cta_button_text`,
      label: 'Call to Action Button Text',
      name: 'cta_button_text',
      type: 'text',
      instructions: 'Text label for primary CTA button.',
      required: 0,
      default_value: 'Get Started Now',
    },
    {
      key: `field_${prefix}_cta_button_url`,
      label: 'Call to Action Button URL',
      name: 'cta_button_url',
      type: 'url',
      instructions: 'Destination URL for primary CTA button.',
      required: 0,
      default_value: '#contact',
    },
    {
      key: `field_${prefix}_featured_badge_color`,
      label: 'Accent Highlight Color',
      name: 'accent_highlight_color',
      type: 'text',
      instructions: 'Hex color code for theme highlights (e.g. #f59e0b).',
      required: 0,
      default_value: '#f59e0b',
    },
  ];

  const customFieldsFormatted = (options.customFields || []).map((cf) => ({
    key: `field_${prefix}_${sanitizeSlug(cf.name).replace(/-/g, '_')}`,
    label: cf.label,
    name: cf.name,
    type: cf.type,
    instructions: cf.instructions || '',
    required: 0,
    default_value: cf.defaultValue || '',
  }));

  const fields = customFieldsFormatted.length > 0 ? customFieldsFormatted : defaultFields;

  return JSON.stringify(
    {
      key: `group_${prefix}_theme_fields`,
      title: `${meta.name} Theme Options & Page Fields`,
      fields,
      location: [
        [
          {
            param: 'post_type',
            operator: '==',
            value: 'page',
          },
        ],
        [
          {
            param: 'post_type',
            operator: '==',
            value: 'post',
          },
        ],
      ],
      menu_order: 0,
      position: 'normal',
      style: 'default',
      label_placement: 'top',
      instruction_placement: 'label',
      hide_on_screen: '',
      active: true,
      description: 'Auto-generated by HTML to WordPress Converter for ACF Local JSON sync',
      show_in_rest: 1,
    },
    null,
    2
  );
}
