import { SourceFile, WordPressThemeFile, WordPressThemeMeta } from '../types';
import { sanitizeSlug } from './converter';

/**
 * Generates WXR XML 1.2 compliant demo content and OCDI configuration files
 */
export function generateDemoContentFiles(
  meta: WordPressThemeMeta,
  sourceFiles: SourceFile[]
): WordPressThemeFile[] {
  const prefix = sanitizeSlug(meta.textDomain || meta.name);
  const files: WordPressThemeFile[] = [];

  const mainHtml = sourceFiles.find((f) => f.type === 'html')?.content || '';
  
  // Extract text pieces from HTML for realistic demo content
  const parser = new DOMParser();
  const doc = parser.parseFromString(mainHtml, 'text/html');
  const pageTitle = doc.querySelector('h1')?.textContent?.trim() || `${meta.name} Home`;
  const heroSubtitle = doc.querySelector('p')?.textContent?.trim() || meta.description;

  // 1. demo-data/content.xml (WordPress eXtended RSS 1.2)
  const wxrXml = `<?xml version="1.0" encoding="UTF-8" ?>
<!-- This is a WordPress eXtended RSS file generated by HTML to WordPress Theme Studio as an export of your site. -->
<!-- It contains information about your site's posts, pages, comments, categories, and other content. -->
<!-- You may use this file to transfer that content from one site to another. -->
<!-- This file is not intended to serve as a complete backup of your site. -->

<!-- To import this information into a WordPress site, follow these steps: -->
<!-- 1. Log in to that site as an administrator. -->
<!-- 2. Go to Tools: Import in the WordPress admin panel. -->
<!-- 3. Install the "WordPress" importer from the list. -->
<!-- 4. Activate & Run Importer. -->
<!-- 5. Upload this file using the form provided on that page. -->

<rss version="2.0"
	xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:wp="http://wordpress.org/export/1.2/"
>

<channel>
	<title>${escapeXml(meta.name)}</title>
	<link>${escapeXml(meta.themeUri || 'https://example.com')}</link>
	<description>${escapeXml(meta.description)}</description>
	<pubDate>Mon, 17 Aug 2026 12:00:00 +0000</pubDate>
	<language>en-US</language>
	<wp:wxr_version>1.2</wp:wxr_version>
	<wp:base_site_url>https://example.com</wp:base_site_url>
	<wp:base_blog_url>https://example.com</wp:base_blog_url>

	<wp:author>
		<wp:author_id>1</wp:author_id>
		<wp:author_login><![CDATA[admin]]></wp:author_login>
		<wp:author_email><![CDATA[admin@example.com]]></wp:author_email>
		<wp:author_display_name><![CDATA[${meta.author || 'Admin'}]]></wp:author_display_name>
		<wp:author_first_name><![CDATA[Demo]]></wp:author_first_name>
		<wp:author_last_name><![CDATA[User]]></wp:author_last_name>
	</wp:author>

	<wp:category>
		<wp:term_id>1</wp:term_id>
		<wp:category_nicename><![CDATA[design]]></wp:category_nicename>
		<wp:category_parent><![CDATA[]]></wp:category_parent>
		<wp:cat_name><![CDATA[Design & Strategy]]></wp:cat_name>
	</wp:category>

	<wp:category>
		<wp:term_id>2</wp:term_id>
		<wp:category_nicename><![CDATA[technology]]></wp:category_nicename>
		<wp:category_parent><![CDATA[]]></wp:category_parent>
		<wp:cat_name><![CDATA[Technology & Web]]></wp:cat_name>
	</wp:category>

	<!-- Demo Home Page -->
	<item>
		<title><![CDATA[${pageTitle}]]></title>
		<link>https://example.com/</link>
		<pubDate>Mon, 17 Aug 2026 12:00:00 +0000</pubDate>
		<dc:creator><![CDATA[admin]]></dc:creator>
		<guid isPermaLink="false">https://example.com/?page_id=2</guid>
		<description></description>
		<content:encoded><![CDATA[<!-- wp:heading {"level":1} -->
<h1>${pageTitle}</h1>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>${heroSubtitle}</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Welcome to your new WordPress website powered by the ${meta.name} theme. This page was automatically configured using One-Click Demo Import data.</p>
<!-- /wp:paragraph -->]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>2</wp:post_id>
		<wp:post_date><![CDATA[2026-08-17 12:00:00]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[2026-08-17 12:00:00]]></wp:post_date_gmt>
		<wp:comment_status><![CDATA[closed]]></wp:comment_status>
		<wp:ping_status><![CDATA[closed]]></wp:ping_status>
		<wp:post_name><![CDATA[home]]></wp:post_name>
		<wp:status><![CDATA[publish]]></wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[page]]></wp:post_type>
		<wp:post_password><![CDATA[]]></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<wp:postmeta>
			<wp:meta_key><![CDATA[_wp_page_template]]></wp:meta_key>
			<wp:meta_value><![CDATA[default]]></wp:meta_value>
		</wp:postmeta>
	</item>

	<!-- Demo Article Post 1 -->
	<item>
		<title><![CDATA[Architecting Next-Generation Digital Experiences]]></title>
		<link>https://example.com/next-gen-experiences</link>
		<pubDate>Mon, 17 Aug 2026 10:00:00 +0000</pubDate>
		<dc:creator><![CDATA[admin]]></dc:creator>
		<guid isPermaLink="false">https://example.com/?p=101</guid>
		<description></description>
		<content:encoded><![CDATA[<p>Modern web architecture blends responsive typography with lightweight asset loading, delivering instantaneous page rendering and accessible interaction across every screen dimension.</p><p>By leveraging native WordPress templates, developers unlock limitless flexibility while retaining intuitive content authoring tools for editors.</p>]]></content:encoded>
		<excerpt:encoded><![CDATA[Discover the core principles of high-performance WordPress development and design.]]></excerpt:encoded>
		<wp:post_id>101</wp:post_id>
		<wp:post_date><![CDATA[2026-08-17 10:00:00]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[2026-08-17 10:00:00]]></wp:post_date_gmt>
		<wp:comment_status><![CDATA[open]]></wp:comment_status>
		<wp:ping_status><![CDATA[open]]></wp:ping_status>
		<wp:post_name><![CDATA[architecting-next-generation-digital-experiences]]></wp:post_name>
		<wp:status><![CDATA[publish]]></wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[post]]></wp:post_type>
		<category domain="category" nicename="design"><![CDATA[Design & Strategy]]></category>
	</item>

	<!-- Demo Article Post 2 -->
	<item>
		<title><![CDATA[Sub-Second Load Times: The Performance Playbook]]></title>
		<link>https://example.com/performance-playbook</link>
		<pubDate>Mon, 17 Aug 2026 09:00:00 +0000</pubDate>
		<dc:creator><![CDATA[admin]]></dc:creator>
		<guid isPermaLink="false">https://example.com/?p=102</guid>
		<description></description>
		<content:encoded><![CDATA[<p>Sub-second website speeds directly correlate with increased user engagement and higher search visibility. Learn how our optimized theme structure eliminates render-blocking bottlenecks.</p>]]></content:encoded>
		<excerpt:encoded><![CDATA[Master the fundamentals of Core Web Vitals optimization in modern WordPress.]]></excerpt:encoded>
		<wp:post_id>102</wp:post_id>
		<wp:post_date><![CDATA[2026-08-17 09:00:00]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[2026-08-17 09:00:00]]></wp:post_date_gmt>
		<wp:comment_status><![CDATA[open]]></wp:comment_status>
		<wp:ping_status><![CDATA[open]]></wp:ping_status>
		<wp:post_name><![CDATA[performance-playbook]]></wp:post_name>
		<wp:status><![CDATA[publish]]></wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[post]]></wp:post_type>
		<category domain="category" nicename="technology"><![CDATA[Technology & Web]]></category>
	</item>
</channel>
</rss>`;

  files.push({
    path: 'demo-data/content.xml',
    name: 'content.xml',
    folder: 'demo-data',
    content: wxrXml,
    language: 'json',
    purpose: 'Standard WordPress eXtended RSS (WXR 1.2 XML) One-Click Demo Content export',
    isCore: false,
  });

  // 2. inc/ocdi-config.php (One Click Demo Import Integration)
  const ocdiPhp = `<?php
/**
 * One Click Demo Import (OCDI) Integration
 *
 * @package ${meta.name}
 */

if (!defined('ABSPATH')) {
    exit;
}

/**
 * Define Demo Import Files for OCDI plugin
 */
function ${prefix}_ocdi_import_files() {
    return array(
        array(
            'import_file_name'           => esc_html__('${meta.name} Default Demo', '${meta.textDomain}'),
            'categories'                 => array('Main Demos'),
            'local_import_file'          => trailingslashit(get_template_directory()) . 'demo-data/content.xml',
            'import_preview_image_url'   => trailingslashit(get_template_directory_uri()) . 'screenshot.png',
            'import_notice'              => esc_html__('After importing this demo, menus and front page settings will be automatically assigned.', '${meta.textDomain}'),
        ),
    );
}
add_filter('ocdi/import_files', '${prefix}_ocdi_import_files');

/**
 * Automatically assign Front Page and Navigation Menus after demo import
 */
function ${prefix}_ocdi_after_import_setup() {
    // Assign Primary Menu
    $main_menu = get_term_by('name', 'Primary Menu', 'nav_menu');
    if ($main_menu) {
        set_theme_mod('nav_menu_locations', array(
            'primary-menu' => $main_menu->term_id,
        ));
    }

    // Set Static Front Page
    $front_page = get_page_by_title('${pageTitle}');
    if ($front_page) {
        update_option('show_on_front', 'page');
        update_option('page_on_front', $front_page->ID);
    }
}
add_action('ocdi/after_import', '${prefix}_ocdi_after_import_setup');
`;

  files.push({
    path: 'inc/ocdi-config.php',
    name: 'ocdi-config.php',
    folder: 'inc',
    content: ocdiPhp,
    language: 'php',
    purpose: 'One Click Demo Import (OCDI) plugin auto-configuration and post-import menu assigner',
    isCore: false,
  });

  return files;
}

function escapeXml(str: string): string {
  return (str || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
